### ISSUE TITLE
dir module not working on elvish 0.15?

### ISSUE THREAD

**Issue by omnibs** [zzamboni/elvish-modules#19]
Absolute beginner in Elvish, sorry if this is something silly, but I just tried this:

```elv
#! /usr/bin/env nix-shell
#! nix-shell -i elvish -p elvish

use epm
epm:install github.com/zzamboni/elvish-modules

use github.com/zzamboni/elvish-modules/dir

use github.com/zzamboni/elvish-modules/alias
alias:new cd "use github.com/zzamboni/elvish-modules/dir; dir:cd"

cd bastion
cd -
```

And got:

```
Exception: compilation error: variable $edit:current-command not found
/Users/juliano/.elvish/lib/github.com/zzamboni/elvish-modules/dir.elv, line 89:   if (> (count $edit:current-command) 0) {
/Users/juliano/git/NoRedInk/tf-all.elv, line 7: use github.com/zzamboni/elvish-modules/dir
```

**Comment by omnibs** [comment]
I learned 0.15.0 is considered old and that this repo is made to work with the latest commits in the elvish repo. Closing.
